# Generated by Django 5.2.3 on 2025-06-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL to be shortened', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='The unique short code used in the shortened URL', max_length=20, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the URL', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the URL was shortened')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the URL was last updated')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the shortened URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the shortened URL is active')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times this shortened URL has been accessed')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp when the URL was last accessed', null=True)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address that created this shortened URL', null=True)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'db_table': 'shortened_urls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='shortened_u_short_c_76171f_idx'), models.Index(fields=['created_at'], name='shortened_u_created_60c958_idx'), models.Index(fields=['is_active'], name='shortened_u_is_acti_458624_idx')],
            },
        ),
        migrations.CreateModel(
            name='URLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the URL was clicked')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who clicked the URL', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the browser', null=True)),
                ('referer', models.URLField(blank=True, help_text='The referring URL', null=True)),
                ('shortened_url', models.ForeignKey(help_text='The shortened URL that was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenedurl')),
            ],
            options={
                'verbose_name': 'URL Click',
                'verbose_name_plural': 'URL Clicks',
                'db_table': 'url_clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['shortened_url', 'clicked_at'], name='url_clicks_shorten_06b8e4_idx'), models.Index(fields=['ip_address'], name='url_clicks_ip_addr_fb4a21_idx')],
            },
        ),
    ]
